e-tms.Solution/e-tms.Web/Models/ManagementViewModels.cs

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

 
namespace e_tms.Web.Models
{
    public class RoleViewModel
    {
        [Required]
        [DisplayName("角色")]
        public string Name { get; set; }
    }
    public class ManagementViewModel
    {
        public ICollection<ApplicationRole> Roles { get; set; }
        public ICollection<ApplicationUser> Users { get; set; }
    }
    public class AccountRecordViewModel
    {
        public ApplicationUser User { get; set; }
        public ICollection<ApplicationRole> Roles { get; set; }
    }
    public class AttachRoleViewModel
    {
        [Required]
        public string UserId { get; set; }
        [Required]
        public string RoleName { get; set; }
    }
    public class AccountViewModel
    {
        [Required]
        [Display(Name = "User Name")]
        public string UserName { get; set; }
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }
        [Required]
        [StringLength(100, ErrorMessage = "密码长度(6-100)。", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "密码")]
        public string Password { get; set; }
    }
}

e-tms.Solution/e-tms.Web/Controllers/ManagementController.cs

 

using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using e_tms.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace e_tms.Web.Controllers
{
    public class ManagementController : Controller
    {
        private ApplicationUserManager userManager;
        private ApplicationRoleManager roleManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                userManager = value;
            }
        }
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                roleManager = value;
            }
        }
        public ManagementController() { }
        public ManagementController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }
        protected override void Dispose(bool disposing)
        {
            //if (disposing && userManager != null)
            //{
            //    userManager.Dispose();
            //    userManager = null;
            //}
            //if (disposing && roleManager != null)
            //{
            //    roleManager.Dispose();
            //    roleManager = null;
            //}
            base.Dispose(disposing);
        }
        private ActionResult _Index()
        {
            ViewBag.RoleSelectList = RoleManager.Roles.Select(r => new SelectListItem { Text = r.Name, Value = r.Name }).ToArray();
            try
            {
                ViewBag.MaxRolesCount = UserManager.Users.Max(u => u.Roles.Count);
            }
            catch(InvalidOperationException ex)
            {
                ViewBag.MaxRolesCount = 0;
            }
            return View("Index", new ManagementViewModel
            {
                Users = UserManager.Users.ToList(),
                Roles = RoleManager.Roles.ToList()
            });
        }
        public ActionResult Index()
        {
            if (RoleManager.Roles.Count() == 0)
            {
                RoleManager.Create(new ApplicationRole() { Name = "admin" });

            }
            return _Index();
        }

         

        [HttpPost]
        [Route("management/roles")]
        public async Task<ActionResult> AddRole(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await RoleManager.CreateAsync(new ApplicationRole { Name = model.Name });
                if (result.Succeeded)
                {
                    //RedirectToAction("Index");
                    return _Index();
                }
                else
                {
                    AddErrors(result);
                }
            }
            return _Index();
        }
        [HttpGet]
        [Route("management/roles/{id}")]
        public async Task<ActionResult> DeleteRole(string id)
        {
            var role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                await RoleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        [Button("Attach")]
        [Route("management/account/roles")]
        public async Task<ActionResult> AttachRole(AttachRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await UserManager.AddToRoleAsync(model.UserId, model.RoleName);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }
            return _Index();
        }
        [HttpPost]
        [Button("Purge")]
        [Route("management/account/roles")]
        public async Task<ActionResult> PurgeRole(AttachRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await UserManager.RemoveFromRoleAsync(model.UserId, model.RoleName);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }
            return _Index();
        }
        [HttpPost]
        [Route("management/account")]
        public async Task<ActionResult> AddAccount(AccountViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser() { UserName = model.UserName, Email = model.Email };
                IdentityResult result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    //return RedirectToAction("Index");
                }
                else
                {
                    AddErrors(result);
                }
            }
            return _Index();
        }
        [HttpGet]
        [Route("management/account/{id}")]
        public async Task<ActionResult> DeleteAccount(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            if (user != null)
            {
                await UserManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }
        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }
    }
}

e-tms.Solution/e-tms.Web/Views/Management/Index.cshtml

@using e_tms.Web.Models
@model ManagementViewModel

@{
    ViewBag.Title = "Role Page";
}



<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>@ViewBag.Title</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">Home</a>
            </li>
            <li>
                <a>系统管理</a>
            </li>
            <li class="active">
                <strong>登录用户</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">

    <div class="ibox-content m-b-sm border-bottom">

        <div class="row">
            <div class="col-lg-12">

                <div class="col-md-4">
                    <h3>角色</h3>

                    @Html.Partial("_AddRolePartial", new RoleViewModel())
                    <br>
                    <table id="role-table" class="table table-bordered">
                        @foreach (var role in Model.Roles)
                        {
                            @Html.Partial("_RoleRecordPartial", role);
                        }
                    </table>
                </div>
                <div class="col-md-8">
                    <h3>用户</h3>
                    @Html.Partial("_AddAccountPartial", new AccountViewModel())
                    <br>
                    <table id="account-table" class="table table-bordered">
                        @foreach (var user in Model.Users)
                        {
                            @Html.Partial("_AccountRecordPartial", new AccountRecordViewModel { User = user, Roles = Model.Roles })
                        }
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>

e-tms.Solution/e-tms.Web/Views/Management/_AccountRecordPartial.cshtml

@using e_tms.Web.Models
@model AccountRecordViewModel

<tr>
    <td>@Model.User.UserName</td>
    @for (int i = 0, max = (int)ViewBag.MaxRolesCount; i < max; i++)
    {
        if (i < Model.User.Roles.Count)
        {
            var role = Model.User.Roles.ElementAt(i);
            <td>@Model.Roles.Single(r => r.Id == role.RoleId).Name</td>
        }
        else
        {
            <td></td>
        }
    }
    <td>
        @Html.Partial("_AttachRolePartial", new AttachRoleViewModel { UserId = Model.User.Id })
    </td>
    <td>
        @Html.Partial("_DeleteAccountPartial", Model.User)
    </td>
</tr>


e-tms.Solution/e-tms.Web/Views/Management/_AddAccountPartial.cshtml

@using e_tms.Web.Models
@model AccountViewModel

@using (Html.BeginForm("Account", "Management", FormMethod.Post, new { @class = "form-inline", role = "form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control", placeholder="User Name" })
    </div>
    <div class="form-group">
        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "E-mail" })
    </div>
    <div class="form-group">
        @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Password" })
    </div>
    <div class="form-group">
        <input type="submit" class="btn btn-primary" value="注册" />
    </div>
}

e-tms.Solution/e-tms.Web/Views/Management/_AddRolePartial.cshtml

@using e_tms.Web.Models
@model RoleViewModel

@using (Html.BeginForm("Roles", "Management", FormMethod.Post, new { @class = "form-inline", role = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder="角色" })
    </div>
    <input type="submit" value="添加" class="btn btn-primary" />
}

e-tms.Solution/e-tms.Web/Views/Management/_AttachRolePartial.cshtml


@using e_tms.Web.Models
@model AttachRoleViewModel

<form action="/management/account/roles" method="post" class="form-inline" role="form">
    @Html.HiddenFor(m => m.UserId)
    <div class="col-md-6">
        @Html.DropDownListFor(m => m.RoleName, (SelectListItem[])ViewBag.RoleSelectList, null, new { @class = "form-control" })
    </div>
    <input type="submit" value="追加" class="btn btn-success" name="Attach"/>
    <input type="submit" value="删除" class="btn btn-warning" name="Purge"/>
</form>

e-tms.Solution/e-tms.Web/Views/Management/_DeleteAccountPartial.cshtml

@using e_tms.Web.Models
@model ApplicationUser

<form action="/management/account/@Model.Id" method="get" class="form-inline" role="form">
    @Html.AntiForgeryToken()
    <input type="submit" value="删除" class="btn btn-danger" />
</form>

e-tms.Solution/e-tms.Web/Views/Management/_RoleRecordPartial.cshtml


@using e_tms.Web.Models

 
@model ApplicationRole

<tr>
    <td>@Model.Name</td>
    <td>
        <form action="/management/roles/@Model.Id" method="get" class="form-inline" role="form">
            @Html.AntiForgeryToken()
            <input type="submit" value="删除" class="btn btn-danger" />
        </form>
    </td>
</tr>